<a href="https://colab.research.google.com/github/AnjaliKM-S/ICT-AKM_2026/blob/main/Case_Study_on_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [10]:
df= pd.read_csv('/content/auto-mpg.csv')

In [3]:
#Load the dataset into a Pandas DataFrame. Display:
#○ The first 10 rows
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [7]:
#○The total number of rows and columns
df.shape

(398, 9)

In [6]:

rows = df.shape[0]
cols = df.shape[1]

print("Rows:", rows)
print("Columns:", cols)

Rows: 398
Columns: 9

In [8]:
#○ Summary statistics for numerical columns
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

####Filtering and Indexing:Find all cars manufactured in 1975 with a weight less than 3000. Return theDataFrame with selected columns: car_name, weight, and mpg

In [15]:
df[(df['weight'] < 3000) & (df['model year'] > 75)][['car name', 'weight', 'mpg']]

            car name  weight   mpg
182         fiat 131    2464  28.0
183        opel 1900    2220  25.0
184         capri ii    2572  25.0
185       dodge colt    2255  26.0
186     renault 12tl    2202  27.0
..               ...     ...   ...
393  ford mustang gl    2790  27.0
394        vw pickup    2130  44.0
395    dodge rampage    2295  32.0
396      ford ranger    2625  28.0
397       chevy s-10    2720  31.0

[141 rows x 3 columns]

###Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [11]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [12]:
df.isna()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
393,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False

In [15]:
##Since 'horsepower' contains '?', we convert it to numeric
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [16]:
df['horsepower'].median()

93.5

In [17]:
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)

/tmp/ipykernel_16939/1826784813.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].median(), inplace=True)

In [18]:
print(df['horsepower'].isnull().sum())

0

##Data Transformation
###Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [20]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']

In [21]:
df[['horsepower', 'weight', 'power_to_weight_ratio']].head()

   horsepower  weight  power_to_weight_ratio
0       130.0    3504               0.037100
1       165.0    3693               0.044679
2       150.0    3436               0.043655
3       150.0    3433               0.043694
4       140.0    3449               0.040591

##Group the cars by origin and calculate the mean mpg for each group.

In [22]:
df['origin'].unique()

array([1, 3, 2])

In [23]:
df.groupby('origin')

In [27]:
df.groupby('origin').get_group(1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,0.040591
...,...,...,...,...,...,...,...,...,...,...
392,27.0,4,151.0,90.0,2950,17.3,82,1,chevrolet camaro,0.030508
393,27.0,4,140.0,86.0,2790,15.6,82,1,ford mustang gl,0.030824
395,32.0,4,135.0,84.0,2295,11.6,82,1,dodge rampage,0.036601
396,28.0,4,120.0,79.0,2625,18.6,82,1,ford ranger,0.030095
397,31.0,4,119.0,82.0,2720,19.4,82,1,chevy s-10,0.030147

In [28]:
df.groupby('origin').get_group(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
14,24.0,4,113.0,95.0,2372,15.0,70,3,toyota corona mark ii,0.040051
18,27.0,4,97.0,88.0,2130,14.5,70,3,datsun pl510,0.041315
29,27.0,4,97.0,88.0,2130,14.5,71,3,datsun pl510,0.041315
31,25.0,4,113.0,95.0,2228,14.0,71,3,toyota corona,0.042639
53,31.0,4,71.0,65.0,1773,19.0,71,3,toyota corolla 1200,0.036661
...,...,...,...,...,...,...,...,...,...,...
382,34.0,4,108.0,70.0,2245,16.9,82,3,toyota corolla,0.031180
383,38.0,4,91.0,67.0,1965,15.0,82,3,honda civic,0.034097
384,32.0,4,91.0,67.0,1965,15.7,82,3,honda civic (auto),0.034097
385,38.0,4,91.0,67.0,1995,16.2,82,3,datsun 310 gx,0.033584
390,32.0,4,144.0,96.0,2665,13.9,82,3,toyota celica gt,0.036023

In [24]:
df.groupby('origin')['mpg']

In [29]:
df.groupby('origin')['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

##Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

In [30]:
df_sorted = df.sort_values(by='mpg', ascending=False)

In [31]:
df_sorted.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
322,46.6,4,86.0,65.0,2110,17.9,80,3,mazda glc,0.030806
329,44.6,4,91.0,67.0,1850,13.8,80,3,honda civic 1500 gl,0.036216
325,44.3,4,90.0,48.0,2085,21.7,80,2,vw rabbit c (diesel),0.023022
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup,0.024413
326,43.4,4,90.0,48.0,2335,23.7,80,2,vw dasher (diesel),0.020557
244,43.1,4,90.0,48.0,1985,21.5,78,2,volkswagen rabbit custom diesel,0.024181
309,41.5,4,98.0,76.0,2144,14.7,80,2,vw rabbit,0.035448
330,40.9,4,85.0,93.5,1835,17.3,80,2,renault lecar deluxe,0.050954
324,40.8,4,85.0,65.0,2110,19.2,80,3,datsun 210,0.030806
247,39.4,4,85.0,70.0,2070,18.6,78,3,datsun b210 gx,0.033816

In [32]:
df.sort_values(by='mpg', ascending=False).head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
322,46.6,4,86.0,65.0,2110,17.9,80,3,mazda glc,0.030806
329,44.6,4,91.0,67.0,1850,13.8,80,3,honda civic 1500 gl,0.036216
325,44.3,4,90.0,48.0,2085,21.7,80,2,vw rabbit c (diesel),0.023022
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup,0.024413
326,43.4,4,90.0,48.0,2335,23.7,80,2,vw dasher (diesel),0.020557
244,43.1,4,90.0,48.0,1985,21.5,78,2,volkswagen rabbit custom diesel,0.024181
309,41.5,4,98.0,76.0,2144,14.7,80,2,vw rabbit,0.035448
330,40.9,4,85.0,93.5,1835,17.3,80,2,renault lecar deluxe,0.050954
324,40.8,4,85.0,65.0,2110,19.2,80,3,datsun 210,0.030806
247,39.4,4,85.0,70.0,2070,18.6,78,3,datsun b210 gx,0.033816

##Create a new column performance_score using a custom function:def performance_score(row): return row['mpg'] * row['acceleration'] / row['weight']

In [33]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

In [34]:
df['performance_score'] = df.apply(performance_score, axis=1)

In [35]:
df[['mpg', 'acceleration', 'weight', 'performance_score']].head()

    mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754

###Visualization PreparationGenerate a summary DataFrame with:Average mpg, weight, and horsepower for each model_year

In [36]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [37]:
summary_df = df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()

In [38]:
summary_df

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

In [39]:
summary_df

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

###Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [40]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [41]:
high_mpg = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]

In [42]:
high_mpg.head()

      mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649

In [43]:
high_mpg.to_csv('high_mpg_cars.csv', index=False)

###Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifically:
###● Calculate the IQR for mpg

In [44]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)

In [45]:
IQR = Q3 - Q1

###Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.

In [46]:
#Define lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [47]:
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]

###Create a DataFrame of cars classified as outliers, displaying car_name, mpg,and model_year.

In [48]:
outliers_df = outliers[['car name', 'mpg', 'model year']]

In [49]:
outliers_df

      car name   mpg  model year
322  mazda glc  46.6          80

#Convert the Pandas dataframe df into numpy using df.values()

In [50]:
import numpy as np

numpy_array = df.values

###Convert the mpg column into a NumPy array and calculate: ○ The mean, median, and standard deviation of mpg. ○ The number of cars with mpg greater than 25.

In [51]:
mpg_array = df['mpg'].to_numpy()

In [52]:
mean_mpg = np.mean(mpg_array)

In [53]:
median_mpg = np.median(mpg_array)
std_mpg = np.std(mpg_array)

In [54]:
count_high_mpg = np.sum(mpg_array > 25)

In [55]:
print("Mean:", mean_mpg)
print("Median:", median_mpg)
print("Standard Deviation:", std_mpg)
print("Cars with mpg > 25:", count_high_mpg)

Mean: 23.514572864321607
Median: 23.0
Standard Deviation: 7.806159061274433
Cars with mpg > 25: 158

###Using NumPy, filter all cars with more than 6 cylinders.Return the corresponding car_name as a list.

In [57]:
import numpy as np

cylinders = df['cylinders'].to_numpy()
car_names = df['car name'].to_numpy()

In [58]:
mask = cylinders > 6

In [59]:
filtered_cars = car_names[mask]

In [60]:
car_list = filtered_cars.tolist()

In [61]:
car_list

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brougham',
 'chevrolet caprice classic',
 'ford ltd',
 'plymouth fury gran sedan',
 'chrysler new yorker brougham',
 'buick electra 225 custom',
 'amc ambassador brougham',
 'chevrolet impala',
 'ford country',
 'plymouth custom suburb',
 'oldsmobile vista cruiser',
 'chevrolet monte carlo s',
 'pontiac grand prix',
 'dodge dart custom',
 'oldsmobile omega',
 'ford gran torino',
 'buick century luxus (sw)',
 'dodge coronet custom (sw)',
 'ford gran torino (sw)',
 'amc matador (sw)',
 'pontiac catalina',
 'chevrolet bel air',
 'plymouth grand fury',
 'ford ltd',
 'chevrolet monza 2+2',
 'ford mustang ii',
 'chevrolet chevelle malibu classic',
 'dodge coronet brougham',
 'amc matador',
 'ford gran torino',
 'plymouth volare premier v8',
 'cadillac seville',
 'chevy c10',
 'ford f108',
 'dodge d100',
 'chevrolet caprice classic',
 'oldsmobile cutlass supreme',
 'dodge monaco brougham',
 'mercury cougar brougham',
 'pontiac grand prix lj',
 'chevrolet monte carlo landau',
 'chrysler cordoba',
 'ford thunderbird',
 'oldsmobile cutlass salon brougham',
 'dodge diplomat',
 'mercury monarch ghia',
 'chevrolet monte carlo landau',
 'ford futura',
 'dodge magnum xe',
 'chevrolet caprice classic',
 'ford ltd landau',
 'mercury grand marquis',
 'dodge st. regis',
 'buick estate wagon (sw)',
 'ford country squire (sw)',
 'chevrolet malibu classic (sw)',
 'chrysler lebaron town @ country (sw)',
 'cadillac eldorado',
 'oldsmobile cutlass salon brougham',
 'oldsmobile cutlass ls']

###Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [62]:
weight_array = df['weight'].to_numpy()

In [63]:
p25 = np.percentile(weight_array, 25)
p50 = np.percentile(weight_array, 50)
p75 = np.percentile(weight_array, 75)

In [64]:
print("25th percentile:", p25)
print("50th percentile (median):", p50)
print("75th percentile:", p75)

25th percentile: 2223.75
50th percentile (median): 2803.5
75th percentile: 3608.0

###Convert the acceleration column into a NumPy array and normalize its values(scale between 0 and 1).

In [65]:
acc_array = df['acceleration'].to_numpy()

In [66]:
min_val = np.min(acc_array)
max_val = np.max(acc_array)

In [67]:
normalized_acc = (acc_array - min_val) / (max_val - min_val)

In [68]:
print(normalized_acc)

[0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619  0.11904762 0.
 0.08928571 0.11904762 0.41666667 0.44642857 0.44642857 0.47619048
 0.38690476 0.74404762 0.56547619 0.38690476 0.56547619 0.26785714
 0.41666667 0.35714286 0.41666667 0.32738095 0.625      0.38690476
 0.44642857 0.35714286 0.6547619  0.29761905 0.44642857 0.44642857
 0.44642857 0.44642857 0.23809524 0.20833333 0.32738095 0.29761905
 0.20833333 0.23809524 0.23809524 0.32738095 0.6547619  0.41666667
 0.38690476 0.35714286 0.35714286 0.68452381 0.38690476 0.6547619
 0.5952381  0.6547619  0.74404762 0.44642857 0.53571429 0.92261905
 0.68452381 0.50595238 0.23809524 0.23809524 0.32738095 0.29761905
 0.20833333 0.17857143 0.32738095 0.32738095 0.26785714 0.32738095
 0.26785714 0.35714286 0.47619048 0.35714286 0.38690476 0.5952381
 0.68452381 0.5952381  0.47619048 0.53571429 0.38690476 0.41666667
 0.50595238 0.29761905 0.20833333 0.29761905 0.38690476 0.26785714
 0.20833333 0.23809524 0.29761905 0.38690476 0.17857143 0.17857143
 0.17857143 0.50595238 0.5952381  0.47619048 0.50595238 0.47619048
 0.77380952 0.35714286 0.26785714 0.29761905 0.26785714 0.41666667
 0.6547619  0.68452381 0.50595238 0.32738095 0.625      0.35714286
 0.44642857 0.29761905 0.08928571 0.68452381 0.44642857 0.35714286
 0.44642857 0.17857143 0.35714286 0.32738095 0.17857143 0.50595238
 0.53571429 0.47619048 0.53571429 0.6547619  0.50595238 0.77380952
 0.53571429 0.53571429 0.5952381  0.50595238 0.35714286 0.38690476
 0.32738095 0.47619048 0.44642857 0.50595238 0.44642857 0.38690476
 0.50595238 0.6547619  0.38690476 0.44642857 0.35714286 0.41666667
 0.44642857 0.47619048 0.47619048 0.47619048 0.77380952 0.68452381
 0.20833333 0.35714286 0.38690476 0.32738095 0.77380952 0.625
 0.6547619  0.6547619  0.41666667 0.32738095 0.23809524 0.47619048
 0.53571429 0.47619048 0.625      0.32738095 0.50595238 0.53571429
 0.38690476 0.35714286 0.53571429 0.41666667 0.53571429 0.38690476
 0.32738095 0.56547619 0.44642857 0.5297619  0.41071429 0.57738095
 0.43452381 0.29761905 0.29761905 0.35119048 0.28571429 0.44047619
 0.38690476 0.57142857 0.57142857 0.8452381  0.83928571 0.36904762
 0.55952381 0.57738095 0.77380952 0.48809524 0.58333333 0.25
 0.53571429 0.5        0.33333333 0.45833333 0.30952381 0.82738095
 0.44642857 0.51785714 0.24404762 0.23809524 0.41666667 0.35714286
 0.625      0.4047619  0.63095238 0.44642857 0.52380952 0.26785714
 0.6547619  0.33928571 0.41071429 0.5        0.5297619  0.57738095
 0.6547619  0.18452381 0.20238095 0.25       0.38690476 0.38690476
 0.47619048 0.60714286 0.46428571 0.53571429 0.4702381  0.5
 0.36309524 0.38690476 0.28571429 0.32738095 0.80357143 0.38095238
 0.67857143 0.63095238 0.5        0.44642857 0.30952381 0.28571429
 0.66666667 0.60714286 0.46428571 0.44047619 0.54761905 0.54761905
 0.46428571 0.51785714 0.63690476 0.42261905 0.30952381 0.32142857
 0.19047619 0.33928571 0.50595238 0.36904762 0.39880952 0.38690476
 0.4047619  0.51785714 0.57142857 0.41071429 0.4702381  0.33333333
 0.45833333 0.46428571 0.41071429 0.51190476 0.44047619 0.60714286
 0.55357143 0.60714286 0.51190476 0.44047619 0.32142857 0.30952381
 0.42857143 0.41071429 0.375      0.41666667 0.29761905 0.35714286
 0.42857143 0.38095238 0.41666667 0.7202381  0.55952381 1.
 0.8452381  0.30952381 0.41071429 0.66666667 0.39880952 0.47619048
 0.19642857 0.29166667 0.30952381 0.39880952 0.64285714 0.44642857
 0.5        0.50595238 0.60119048 0.7202381  0.63690476 0.46428571
 0.44642857 0.56547619 0.41666667 0.42857143 0.58928571 0.38095238
 0.66666667 0.81547619 0.93452381 0.70833333 0.82142857 0.3452381
 0.55357143 0.5952381  0.43452381 0.20238095 0.26785714 0.42261905
 0.375      0.53571429 0.45833333 0.5        0.38095238 0.27380952
 0.29166667 0.5297619  0.5        0.48214286 0.58333333 0.67857143
 0.55357143 0.47619048 0.41071429 0.48809524 0.75595238 0.36904762
 0.46428571 0.38095238 0.52380952 0.4047619  0.61309524 0.73809524
 0.69047619 0.27380952 0.3452381  0.46428571 0.6547619  0.54166667
 0.51190476 0.69047619 0.63095238 0.5952381  0.48809524 0.47619048
 0.5952381  0.5        0.74404762 0.43452381 0.60714286 0.57142857
 0.39880952 0.55357143 0.38690476 0.38690476 0.5297619  0.41666667
 0.45833333 0.48809524 0.5        0.53571429 0.38690476 0.39880952
 0.35119048 0.29761905 0.55357143 0.45238095 0.98809524 0.21428571
 0.63095238 0.67857143]

###Increase all horsepower values by 10% and store the updated values in a newNumPy array. Handle missing data (if any) by replacing it with the mean of the column before applying the increase.

In [69]:
hp = pd.to_numeric(df['horsepower'], errors='coerce').to_numpy()

In [74]:
mean_hp = np.nanmean(hp)
hp_clean = np.where(np.isnan(hp), mean_hp, hp)

In [70]:
mean_hp = np.nanmean(hp)

In [75]:
hp_updated = hp_clean * 1.10

In [76]:
print(hp_updated)

[143.   181.5  165.   165.   154.   217.8  242.   236.5  247.5  209.
 187.   176.   165.   247.5  104.5  104.5  106.7   93.5   96.8   50.6
  95.7   99.   104.5  124.3   99.   236.5  220.   231.   212.3   96.8
  99.   104.5  102.85 110.   115.5  110.    96.8  110.   181.5  192.5
 168.3  165.   198.   187.   192.5  121.    79.2  110.    96.8   94.6
  99.    77.    83.6   71.5   75.9   66.    77.   104.5   88.    59.4
  99.    94.6  181.5  192.5  165.   168.3  165.   228.8  170.5  176.
 209.   106.7  165.   143.   154.   165.   123.2   83.6   95.7   75.9
  94.6  101.2  106.7   88.    96.8  192.5  165.   159.5  150.7  165.
 217.8  165.   173.8  165.   236.5  247.5  192.5  115.5  110.   110.
  96.8  104.5   50.6  165.   183.7  187.   198.   110.    96.8   79.2
 103.4   99.    93.5  117.7   99.   159.5  253.    53.9   82.5  100.1
 123.2  165.   121.   134.2  198.   104.5  102.85 110.   110.    73.7
  88.    71.5   82.5  110.   121.   115.5  154.   165.   165.   154.
 165.    91.3   73.7   85.8   57.2   67.1   82.5   82.5   82.5  106.7
 102.3   73.7  104.5  115.5   79.2   79.2  187.   159.5  165.   162.8
 121.   115.5  121.   104.5  121.   121.   141.9   82.5   91.3  110.
  85.8  105.6   78.1  106.7  106.7   77.    99.   104.5   96.8  107.8
 126.5   58.3   94.6   89.1  101.2   86.9   91.3  154.   165.   132.
 167.2  110.   115.5   89.1   99.    57.2   66.    77.    58.3  110.
  85.8  121.   104.5   78.1   77.    82.5   79.2  112.2  165.    96.8
 118.8  132.   198.   159.5  143.   165.    74.8   88.    63.8  105.6
  77.   159.5  121.   159.5  143.   121.   115.5  110.   107.8  198.
 187.   209.   163.9   85.8   96.8   82.5   97.9   69.3   91.3   73.7
  85.8  106.7  121.   121.    52.8   72.6   57.2   77.    66.   121.
 154.   152.9  115.5  104.5   93.5   96.8  110.    99.   115.5   93.5
 121.   132.   159.5  181.5  152.9  154.    74.8  104.5  106.7   82.5
 104.5  115.5   93.5  106.7  113.3  137.5  126.5  146.3   78.1   74.8
 126.5   93.5   96.8   99.   121.   143.   141.9  151.8  148.5  170.5
 156.2  137.5  165.    78.1   71.5   88.    88.    84.7  137.5   78.1
  99.    77.    77.    71.5   75.9   99.   126.5  126.5   99.    83.6
  66.    77.    71.5   99.    96.8   99.    99.    85.8   99.    82.5
 101.2   82.5   71.5  115.5   71.5   52.8   52.8   73.7   73.7   73.7
 102.85  73.7   68.2  145.2  110.    96.8  102.85  79.2   92.4   92.4
 101.2  121.    92.4   63.8   70.4   66.    73.7   71.5   68.2   74.8
  69.3   71.5   71.5   81.4  102.85  82.5   82.5  110.    81.4   88.
  83.6  127.6  132.   121.   115.5   96.8   93.5   96.8   96.8   96.8
  93.5   92.4   99.   101.2  102.85  81.4   74.8   74.8   69.3   77.
  96.8   82.5   77.    73.7   73.7   73.7  121.    93.5  101.2  123.2
 105.6   92.4   99.    94.6   57.2   92.4   86.9   90.2 ]

###Find the average displacement of cars with an origin of 2 (Europe) using NumPyindexing.

In [77]:
origin = df['origin'].to_numpy()

In [78]:
displacement = df['displacement'].to_numpy()

In [79]:
mask = origin == 2

In [81]:
europe_disp = displacement[mask]

In [82]:
avg_disp = np.mean(europe_disp)

In [83]:
print(avg_disp)

109.14285714285714

###Create a 2D NumPy array containing the columns mpg, horsepower, and weight.Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [84]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [85]:
matrix = df[['mpg', 'horsepower', 'weight']].to_numpy()

In [86]:
vector = np.array([1, 0.5, -0.2])

In [87]:
result = np.dot(matrix, vector)

In [88]:
print(result)

[-617.8  -641.1  -594.2  -595.6  -602.8  -754.2  -746.8  -740.9  -758.5
 -660.   -612.6  -627.8  -662.2  -490.7  -402.9  -497.1  -488.3  -453.9
 -355.   -318.   -465.9  -417.   -402.5  -364.3  -463.6  -805.5  -765.2
 -760.4  -840.9  -355.   -379.8  -373.1  -337.45 -457.8  -619.3  -598.8
 -597.4  -589.6  -745.3  -791.3  -740.3  -730.2  -889.   -851.2  -927.5
 -519.4  -423.6  -587.4  -565.8  -378.   -351.6  -349.8  -345.   -291.1
 -253.1  -309.8  -330.   -384.1  -360.2  -400.8  -416.6  -381.2  -759.3
 -775.5  -737.   -735.3  -642.4  -811.6  -809.9  -799.2  -776.4  -398.5
 -688.4  -741.6  -775.8  -726.4  -512.6  -442.2  -531.3  -377.3  -414.
 -383.6  -429.7  -364.8  -349.   -719.5  -645.4  -712.1  -725.9  -665.4
 -879.4  -804.8  -780.6  -758.4  -826.5  -865.7  -663.7  -553.7  -589.6
 -521.   -542.2  -510.3  -341.   -913.4  -885.7  -832.8  -797.8  -489.8
 -391.8  -423.2  -406.8  -361.8  -400.5  -419.9  -382.   -728.9  -724.6
 -319.9  -370.1  -450.9  -498.6  -589.8  -453.   -480.4  -631.8  -552.9
 -507.25 -511.2  -602.2  -325.5  -424.2  -302.7  -445.9  -690.2  -655.4
 -652.1  -742.2  -851.8  -802.4  -843.6  -762.4  -373.3  -333.1  -395.
 -272.8  -338.1  -359.5  -360.1  -385.7  -425.3  -405.7  -335.5  -586.3
 -621.3  -635.4  -580.6  -832.6  -800.5  -808.6  -843.4  -709.4  -710.9
 -676.   -691.5  -531.8  -569.2  -556.3  -367.7  -463.3  -512.8  -456.4
 -468.4  -384.1  -436.5  -530.3  -323.4  -578.2  -468.3  -524.4  -518.
 -451.7  -299.5  -421.8  -378.5  -443.4  -385.5  -371.9  -755.5  -747.
 -716.9  -752.5  -574.6  -596.1  -537.9  -549.5  -352.   -378.3  -323.4
 -299.5  -660.2  -657.8  -655.5  -573.6  -300.   -331.   -365.5  -450.5
 -559.   -700.   -591.   -513.   -687.5  -769.5  -725.5  -696.   -663.
 -343.5  -361.   -300.   -386.5  -320.5  -686.   -740.   -740.   -779.
 -631.5  -612.   -657.   -637.5  -738.   -732.5  -754.5  -776.5  -320.
 -479.5  -389.5  -481.   -348.2  -340.   -333.5  -368.5  -492.5  -443.5
 -467.5  -329.9  -290.9  -338.2  -339.6  -293.9  -598.1  -657.6  -624.3
 -635.3  -563.   -530.3  -474.9  -615.5  -577.6  -602.9  -550.7  -650.4
 -603.9  -593.3  -588.8  -553.4  -728.5  -367.   -437.   -384.3  -377.6
 -434.4  -473.3  -504.7  -408.6  -494.2  -548.5  -479.9  -599.3  -331.
 -363.5  -570.   -535.7  -511.7  -587.8  -596.4  -686.   -662.9  -705.5
 -680.3  -777.6  -724.3  -639.3  -694.5  -317.6  -328.4  -307.3  -466.6
 -642.1  -694.5  -575.3  -615.1  -370.8  -360.5  -339.7  -354.2  -460.6
 -432.7  -455.7  -432.7  -349.3  -325.5  -356.9  -334.1  -462.6  -503.6
 -531.3  -612.1  -364.3  -467.4  -439.6  -403.8  -383.3  -342.9  -479.6
 -348.7  -348.7  -399.6  -520.1  -586.5  -291.9  -279.35 -361.7  -308.2
 -483.3  -410.3  -421.   -510.65 -389.6  -428.8  -458.4  -452.2  -466.5
 -405.   -282.9  -304.   -286.9  -347.2  -325.5  -341.3  -328.9  -376.8
 -342.1  -413.6  -368.   -382.75 -370.8  -400.1  -440.1  -458.4  -577.9
 -563.3  -496.6  -501.8  -605.6  -665.9  -547.8  -632.9  -449.   -457.
 -401.   -441.5  -434.   -475.   -503.   -537.25 -323.   -334.   -329.
 -355.5  -354.   -352.   -367.5  -380.   -321.5  -327.5  -327.5  -509.
 -522.5  -445.   -489.   -453.   -396.   -518.   -488.   -356.   -385.
 -457.5  -472.  ]

###Use NumPy to sort the cars by model_year in descending order and display the firstfive car names

In [89]:
import numpy as np

model_year = df['model year'].to_numpy()
car_names = df['car name'].to_numpy()

In [90]:
sorted_indices = np.argsort(model_year)[::-1]

In [91]:
sorted_car_names = car_names[sorted_indices]

In [92]:
top5_cars = sorted_car_names[:5]

In [93]:
print(top5_cars)

['dodge aries se' 'pontiac phoenix' 'pontiac j2000 se hatchback'
 'chevrolet cavalier 2-door' 'chevrolet cavalier wagon']

###Compute the Pearson correlation coefficient between mpg and weight using NumPy

In [94]:
import numpy as np

mpg = df['mpg'].to_numpy()
weight = df['weight'].to_numpy()

In [95]:
corr_matrix = np.corrcoef(mpg, weight)

In [96]:
correlation = np.corrcoef(mpg, weight)[0, 1]

In [97]:
print("Pearson correlation:", correlation)

Pearson correlation: -0.8317409332443352

###Calculate the mean mpg for cars grouped by the number of cylinders using NumPytechniques.

In [98]:
cylinders = df['cylinders'].to_numpy()
mpg = df['mpg'].to_numpy()

In [99]:
unique_cyl = np.unique(cylinders)

In [100]:
for cyl in unique_cyl:
    avg = np.mean(mpg[cylinders == cyl])

In [101]:
  print("Cylinders:", cyl, "Average MPG:", avg)

Cylinders: 8 Average MPG: 14.963106796116506